// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5J-hCK5sOmYkn-53PHun86lTIL-c3thc',
    appId: '1:506638171988:web:de4b3fe2566aa0579212c1',
    messagingSenderId: '506638171988',
    projectId: 'e-commerce-app-582aa',
    authDomain: 'e-commerce-app-582aa.firebaseapp.com',
    storageBucket: 'e-commerce-app-582aa.appspot.com',
    measurementId: 'G-M5N6C0J8FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0yK0vGXd4n6A0toLgqaOJxnnU9bdPE8w',
    appId: '1:506638171988:android:b77dba9f20669a769212c1',
    messagingSenderId: '506638171988',
    projectId: 'e-commerce-app-582aa',
    storageBucket: 'e-commerce-app-582aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmmIQQF-jteWwOM_D3Y8KblUOd7WfRFjo',
    appId: '1:506638171988:ios:10326a12ecb5e2fb9212c1',
    messagingSenderId: '506638171988',
    projectId: 'e-commerce-app-582aa',
    storageBucket: 'e-commerce-app-582aa.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5J-hCK5sOmYkn-53PHun86lTIL-c3thc',
    appId: '1:506638171988:web:d66d54efecf7d2dc9212c1',
    messagingSenderId: '506638171988',
    projectId: 'e-commerce-app-582aa',
    authDomain: 'e-commerce-app-582aa.firebaseapp.com',
    storageBucket: 'e-commerce-app-582aa.appspot.com',
    measurementId: 'G-BENVD2G7B4',
  );
}
